language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
install:
  - bundle install
  - gem install 'test-unit'
  - gem install rubocop
  - echo 9999 > VERSION
  - gem build mpw.gemspec
  - gem install mpw-9999.gem
script:
  - rubocop
  - ruby ./test/tests.rb 
